import { defineField, defineType } from "sanity";

export const experience = defineType({
  name: "experience",
  title: "Experience",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "practical", title: "Practical Details" },
    { name: "media", title: "Media" },
    { name: "related", title: "Related" },
  ],
  fields: [
    defineField({ name: "title", title: "Title", type: "localeString", group: "content" }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title.en" },
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category (Mandala Pengalaman pillar)",
      type: "string",
      group: "content",
      options: {
        list: [
          { title: "Heritage & Culture", value: "heritage" },
          { title: "Arts & Learning", value: "arts" },
          { title: "Culinary", value: "culinary" },
          { title: "Community & Creative Life", value: "community" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "destination",
      title: "Destination",
      type: "reference",
      to: [{ type: "destination" }],
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "audiences",
      title: "Audiences",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "Cultural traveler", value: "cultural-traveler" },
          { title: "Family or small group", value: "family" },
          { title: "School or community", value: "school-community" },
          { title: "Corporate or institution", value: "corporate" },
          { title: "International visitor", value: "international-visitor" },
        ],
      },
    }),
    defineField({ name: "durationHours", title: "Approximate duration (hours)", type: "number", group: "content" }),
    defineField({
      name: "languages",
      title: "Languages available",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({ name: "summary", title: "One-sentence promise", type: "localeString", group: "content" }),
    defineField({ name: "story", title: "Story", type: "localeText", group: "content" }),
    defineField({
      name: "highlights",
      title: "Highlights (3-5 moments)",
      type: "array",
      group: "content",
      of: [{ type: "localeString" }],
    }),
    defineField({ name: "meetingPoint", title: "Meeting point", type: "localeString", group: "practical" }),
    defineField({ name: "minimumGroup", title: "Minimum group", type: "localeString", group: "practical" }),
    defineField({ name: "accessibility", title: "Accessibility", type: "localeText", group: "practical" }),
    defineField({ name: "whatToBring", title: "What to bring", type: "localeText", group: "practical" }),
    defineField({
      name: "includes",
      title: "Includes",
      type: "array",
      group: "practical",
      of: [{ type: "localeString" }],
    }),
    defineField({
      name: "excludes",
      title: "Excludes",
      type: "array",
      group: "practical",
      of: [{ type: "localeString" }],
    }),
    defineField({
      name: "responsibleVisitNotes",
      title: "Responsible visit notes",
      type: "localeText",
      group: "practical",
    }),
    defineField({
      name: "images",
      title: "Gallery images",
      type: "array",
      group: "media",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [{ name: "alt", title: "Alt text", type: "localeString" }],
        },
      ],
    }),
    defineField({
      name: "relatedExperiences",
      title: "Related experiences",
      type: "array",
      group: "related",
      of: [{ type: "reference", to: [{ type: "experience" }] }],
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: "relatedStories",
      title: "Related stories",
      type: "array",
      group: "related",
      of: [{ type: "reference", to: [{ type: "story" }] }],
    }),
    defineField({
      name: "priceOnRequest",
      title: "Price on request",
      description: "Keep enabled until a verified retail price is approved by commercial and operations (PRD section 9).",
      type: "boolean",
      initialValue: true,
      group: "content",
    }),
    defineField({
      name: "retailPrice",
      title: "Verified retail price (IDR)",
      type: "number",
      group: "content",
      hidden: ({ document }) => Boolean(document?.priceOnRequest),
    }),
    defineField({
      name: "priceUnit",
      title: "Price unit",
      type: "string",
      group: "content",
      options: {
        list: [
          { title: "Per person", value: "per-person" },
          { title: "Per group / package", value: "per-group" },
        ],
      },
      initialValue: "per-person",
      hidden: ({ document }) => Boolean(document?.priceOnRequest),
    }),
    defineField({
      name: "inquiryStatus",
      title: "Inquiry status",
      type: "string",
      group: "content",
      options: {
        list: [
          { title: "Open", value: "open" },
          { title: "Seasonal", value: "seasonal" },
          { title: "On request", value: "on-request" },
        ],
      },
      initialValue: "on-request",
    }),
  ],
  preview: {
    select: { title: "title.en", subtitle: "category", media: "images.0" },
  },
});
